### PR TITLE
Add /widget/contactform.tpl used by widget render

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add the /widget/contactform.tpl call in renderWidget() method.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27521.
| How to test?  |  Make the sames steps as issue, with this Pull Request fetched.

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Isn't it a duplication of https://github.com/PrestaShop/contactform/blob/dev/views/templates/hook/contactform.tpl ?

Can we find a way to have a unique code reused in multiple places instead of duplicating the code?

**Comment by PrestaEdit** [comment]
Arf, to be honest, I didn't see something: there is no use of the base template.
It's never used, we surely could delete the others template, here.

**Comment by NeOMakinG** [comment]
> Arf, to be honest, I didn't see something: there is no use of the base template. It's never used, we surely could delete the others template, here.

What if some people used it in their theme/modules? Maybe they can both extend the same codebase or one extend the other

**Comment by PrestaEdit** [comment]
If they use it, there will be no problem.

As the template is not called by the module, it's mean that they have made a speicif change/handle inside their theme.
Or that it's a PrestaShop 1.6 version of PrestaShop. As the module is no more compliant with, it's not a problem.

**Comment by NeOMakinG** [comment]
> If they use it, there will be no problem.
> 
> As the template is not called by the module, it's mean that they have made a speicif change/handle inside their theme. Or that it's a PrestaShop 1.6 version of PrestaShop. As the module is no more compliant with, it's not a problem.

Yeah but this is probably why we can't delete the unused file, or we need to tag it as a BC (I wouldn't mind if you delete it honestly)

**Comment by PrestaEdit** [comment]
I'm not really sure. This file is not called/used. Really.
There is already 6 years since this module is with this fault.

Really, no theme can use it as this. It's necessary to have the widget template inside all theme.

**Review by NeOMakinG — DISMISSED** [review]
Anyway, the template should exist as the module use it, let's accept this 👍

**Comment by matks** [comment]
> The module is still broken when installed in a context outside of the "classic" theme :(

I am sorry but this PR seems to copy-paste the content of https://github.com/PrestaShop/contactform/blob/dev/views/templates/hook/contactform.tpl

Duplicating code is usually not OK :/ it can be done in some specific situations but here I don't think it's relevant. We should not merge something fast if it brings future issues

**Comment by NeOMakinG** [comment]
> > The module is still broken when installed in a context outside of the "classic" theme :(
> 
> I am sorry but this PR seems to copy-paste the content of https://github.com/PrestaShop/contactform/blob/dev/views/templates/hook/contactform.tpl
> 
> Duplicating code is usually not OK :/ it can be done in some specific situations but here I don't think it's relevant. We should not merge something fast if it brings future issues

Just remove that file then, because `/hook/contactform.tpl` is not used at all in the module

**Comment by okom3pom** [comment]
I can confirm the bug, The change was made to respect a minimum the validator. 

I prefer a warning on the validator than asking people to redo their themes

Just move the file to the right place without creating another one.

**Comment by PrestaEdit** [comment]
Hello everyone,

It's seems that it's still in waiting for author there.

To answer you, the module it's not working in stand alone and so outstide the classic-theme or theme that have managed the template.

Using this module in widget mode say that you need this template  : https://github.com/PrestaShop/contactform/blob/dev/contactform.php#L243

Of course, there, the content it's the same than the classic theme. If your theme using this module, it will surely have this template already set or the module will throw an error in the usage.

This remove the needs for each theme to use it's own tpl for the use of this module.

**Comment by tups** [comment]
Why this module would not have the right to work in standalone?

Why should someone new to creating a new theme end up with this error? Especially when it's a module error, where it was forgotten to put the default template?

I do not understand that this PR is still not validated. It does not impact any project (because as @PrestaEdit said anyway all theme creators had to copy the template into their theme to correct this error), and this will make this module more reliable.

**Comment by kpodemski** [comment]
Hello @PrestaEdit 

Maybe you should follow @okom3pom suggestion and simply move the file from one location to another instead of copying it?

**Pull request closed without merging**
