### PR TITLE
Confirmation text after settings change

### LINKED ISSUE #21381: [BO] [Modules] Confirmation of changes message is not displayed
#### Describe the bug

On module contactform and ps_shoppingcart, when I switch the toggles to YES / NO then click save, I don't have the confirmation message on top 

#### Expected behavior

A confirmation message as follow "The settings have been successfully updated."
Capture d’écran 2020-10-09 à 14 41 08

#### Steps to Reproduce

1. Search for contactform & ps_shoppingcart
2. Switch the toggles YES / NO
=> The confirmation message doesnt appear

#### Additional information

* PrestaShop version: 1.7.8.x & 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Confirmation text after settings change
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21381
| How to test?  | Change settings, make sure that confirmation text is displayed
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by matks** [comment]
Hi @kpodemski I'm puzzled 😅 the issue mentions a missing message but your PR introduces a redirect. I am 100% sure I'm missing some information 😬 can you enlight me ?

**Comment by kpodemski** [comment]
😅 welcome to PrestaShop @matks

This is how you handle confirmation messages on legacy pages, it's a super oldschool way of "flash messages" 😅 

Thanks to this `&conf` AdminController knows that proper confirmation message has to be displayed, list of available messages is here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L480

Why redirect? To avoid sending form again on page refresh 🤷‍♂️

**Comment by matks** [comment]
> 😅 welcome to PrestaShop @matks
> 
> This is how you handle confirmation messages on legacy pages, it's a super oldschool way of "flash messages" 😅

So this `conf=6` was the secret behind all that 😅 well it's hard to guess when you dont know about it

**Comment by kpodemski** [comment]
Yeah, **there's a lot** of stuff like this in Core 🤷 but! see, you only have to add one param and if you want to change this text you're doing it in one place 😅

**Review by atomiix — APPROVED** [review]

**Comment by ngodefroy** [comment]
@kpodemski 
TEST IS OK
Capture d’écran 2020-10-09 à 18 02 29
Thank you :)

**Comment by atomiix** [comment]
Thanks @kpodemski & @ngodefroy !

**Pull request merged**
