### PR TITLE
Change folder name for contactform.tpl

### LINKED ISSUE #35746: contactform module - Incorrect path to TPL file
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the contactform module is a path to contactform.tpl defined in incorrect way.

In the module is path defined as:
`return $this->display(__FILE__, 'views/templates/widget/contactform.tpl');`

but contactform.tpl file is in the module structure in the path:
`views/templates/hook/`

Vice versa in the theme override is contactform.tpl file present in the path:
` themes/classic/modules/contactform/views/templates/widget/`

It should be unified because when the module will be used with 3rd party theme without overrided contactform.tpl file, the module itself will wont find contactform.tpl file in the module folder.

### Expected behavior

_No response_

### Steps to reproduce

1. install contactform module
2. delete /themes/classic/modules/contactform/views/templates/widget/contactform.tpl
3. Contact page will return message "No template found for module contactform"

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

contactform v4.4.2

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Touxten**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | In the contactform module is a path to contactform.tpl defined in incorrect way.
| Type?         | bug fix
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/35746
| How to test?  | See issue
| Sponsor company| @Touxten 

For BC break i am not sur because the file is not used ?

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @Touxten!

This is your first pull request on [contactform](https://github.com/PrestaShop/contactform/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by kpodemski** [comment]
Hello @Touxten 

Since it hasn’t worked, I think it is not a BC Break. I'll ping @Hlavtox for a second opinion.

If that would’ve been a BC break, then the process is as follows:
- you make a change
- you describe why it is required to introduce a new major version (e.g., there are backward incompatible changes inside)
- you ping committers to create a new milestone for the new major version (if it doesn’t exist already)
- It should then force us to release it as a major version.

**Review by kpodemski — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]
It's not a BC break, it never worked, so people may never use it. :-)

**Comment by Hlavtox** [comment]
@Touxten Can you bump the version in php and xml file to 4.4.3?

**Comment by Touxten** [comment]
Done @kpodemski && @Hlavtox

**Review by Hlavtox — APPROVED** [review]

**Pull request merged**
