### PR TITLE
Release 4.4.1

### PR DESCRIPTION
**Pull request by kpodemski**
Release PR.

### CODE REVIEW

**Comment by kpodemski** [comment]
@hibatallahAouadni I think there's no need to re-tests anything. You've just tested it, there's only one change 👍🏻

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@kpodemski But that is the process 🤔

**Comment by hibatallahAouadni** [comment]
@kpodemski just quick re-check 😉 don't worry

**Comment by kpodemski** [comment]
@hibatallahAouadni but why, you've just tested it, there are no other differences between main and `develop` branch 🙄

**Comment by Hlavtox** [comment]
@kpodemski You don't understand, it's the process!

**Review by hibatallahAouadni — APPROVED** [review]
Hello @kpodemski 

Thanks for your patience 🙏 
LGTM, QA ✅ 

Thanks!

**Pull request merged**
