### PR TITLE
Modules - Buttons should be updated

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Modules - Buttons should be updated see https://github.com/PrestaShop/PrestaShop/issues/21361
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21361
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/21361 by @khouloudbelguith

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by ngodefroy** [comment]
@PululuK When I change the switchers to NO / YES, I don't have the confirmation message 

https://drive.google.com/file/d/1-dDe3bz6EHLlWcsbn46X7mpjU-JmdxoD/view

Thank you

**Comment by PululuK** [comment]
> @PululuK When I change the switchers to NO / YES, I don't have the confirmation message
> 
> https://drive.google.com/file/d/1-dDe3bz6EHLlWcsbn46X7mpjU-JmdxoD/view
> 
> Thank you

@ngodefroy  what the relation with my PR?

**Comment by ngodefroy** [comment]
> @ngodefroy what the relation with my PR?
> Please open another issue for this ! And you can assign it to me.

@PululuK Thought it might be linked..I will open another issue ;)

**Comment by PululuK** [comment]
> > @ngodefroy what the relation with my PR?
> > Please open another issue for this ! And you can assign it to me.
> 
> @PululuK Thought it might be linked..I will open another issue ;)

Thanks ! finally @kpodemski will handle this.

**Comment by PululuK** [comment]
@ngodefroy  can you remove **waiting for author** label please ?

**Comment by Progi1984** [comment]
Thanks @PululuK & @ngodefroy

**Pull request merged**
