### PR TITLE
Fix issue 9566

### PR DESCRIPTION
**Pull request by marionf**
Fix issue https://github.com/PrestaShop/PrestaShop/issues/9566

### CODE REVIEW

**Comment by eternoendless** [comment]
I don't think this change actually changes any behavior. Did you manage to reproduce the problem and fix it with this change?

**Comment by marionf** [comment]
No, I didn't manage to reproduce the issue
This fix doesn't change anything for me, I just applied the changes suggested by @maofree

**Comment by maofree** [comment]
I reproduced the error on  some sites (different hosting)
with this change all is ok, without there is a problem to send email
and it happens only with this module
the rest can send email

**Comment by PierreRambaud** [comment]
I close this pull request since this actually do not change any behavior and I am still able to reproduce the error with or without this patch.

**Pull request closed without merging**
