### PR TITLE
Check if customer is the owner of the selected order

### PR DESCRIPTION
**Pull request by PierreRambaud**
When posting a message, even if I'm not connected, I can send a `id_order` and inject message into someone order. 
Look my second commit, the first one is because I wasn't able to read this class.

Fixed bug: http://forge.prestashop.com/browse/BOOM-4362

### CODE REVIEW

**Comment by rGaillard** [comment]
@PierreRambaud, that will not work anymore if the customer is not logged but send an id_customer_thread with its token.

**Comment by PierreRambaud** [comment]
@rGaillard You can't send anymore an id_order when you're not logged, no field available, you can only inject it.

**Comment by rGaillard** [comment]
@PierreRambaud no the field id_order is available when you send an id_customer_thread (cf your link). But this is done before sending the message, you reset the id_order when the customer is not logged, so it can't retrieve the id_customer_thread: https://github.com/PierreRambaud/contactform/blob/e3090f260046f074fe4b6271cd88d830647061bc/contactform.php#L508

**Comment by PierreRambaud** [comment]
@rGaillard Aaahhh, Nice catch, I know what you mean :) I change the condition to only check if the selector order is own by the selected customer (getting by email  / connected)

**Comment by eternoendless** [comment]
Thank you @PierreRambaud

**Pull request merged**
