### PR TITLE
Adding ability to use google reCaptcha V2.

### PR DESCRIPTION
**Pull request by LedCloud**
The captcha is beeing shown only when:
1) the user is not logged in AND
2) the option to use it is set on.

### CODE REVIEW

**Comment by wjurkowlaniec** [comment]
hey that's great to get functionality, @PrestaShop/prestashop-core-developers why aren't you reviewing PR's

**Comment by PierreRambaud** [comment]
@wjurkowlaniec Because we are not enough to review all repositories :sob: 
But thanks for the reminder :+1: 

@LedCloud We are really sorry for the dealy, your pull request looks very good and very interesting.
Are you able to rebase it? I'll approve it just after :smile_cat:

**Comment by NeOMakinG** [comment]
@LedCloud we're waiting for a rebase to approve :)

**Comment by LedCloud** [comment]
I don't quite understand what should I do.

**Comment by NeOMakinG** [comment]
Hey, I suggest you to try it, this is not that hard on such a PR

Add a remote upstream to your local git : git remote add upstream git@github.com:PrestaShop/contactform.git

or use http url, depends of your use
then :
git checkout dev
git pull upstream dev
git checkout recaptcha
git rebase dev

If you have some conflict, resolve them and git add the files
then
git rebase --continue

Same thing with conflicts, then when it's fine

git push -f

Hope it helps !

**Comment by LedCloud** [comment]
I failed and created new PR https://github.com/PrestaShop/contactform/pull/34

**Comment by Progi1984** [comment]
Ok. So i close this one @LedCloud ;) Thanks

**Pull request closed without merging**
